# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: E2E Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Setup Python
      uses: actions/setup-python@v5.0.0
      with:
        python-version: 3.12   
    - name:  Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Browser init
      run: rfbrowser init
    - name: Run E2E tests
     # run: robot -d ./logs -i smoke tests # adicionando parametro para rodar somente teste com a alguma tag
      run: robot -d ./logs ./tests
    - name: Robot Report
      uses: joonvena/robotframework-reporter-action@v2.4
      with:
        gh_access_token: ${{ secrets.GITHUB_TOKEM }}
        report_path: logs
